### ISSUE TITLE
Improve the decision agent

### ISSUE THREAD

**Issue by vorcigernix** [smartsupp/openapi-client#19]
We need to improve the main decision agent to make sure that it recognizes at least two main use cases. One would be a SmartShopper itself and second will be a more generic agent answering from the context. 

- [ ] sub agent for SmartShopper identifies itself for the correct intent
- [ ] generic sub agent recognizes a generic question and tries to respond
- [ ] master agent parse the question and ask the correct sub agent for a response
- [ ] all agents exit gracefully if there is no valid answer

**Comment by dkMorlok** [comment]
wrong repo?

**Comment by vorcigernix** [comment]
Haha, no, just playing around with it.  I mean, github projects.

**Comment by jkasztur** [comment]
wrong repo, closing
